schema = 3

[mod]
  [mod."cel.dev/expr"]
    version = "v0.25.2"
    hash = "sha256-J8C2tbW9PcXA71UhcEdyXPR8vmqkEiapZk/RnZz3qyo="
  [mod."cloud.google.com/go"]
    version = "v0.123.0"
    hash = "sha256-OjuvlqYrGvoUiXO/5ALbMxHvXRlrhDjLby1BN/nuhAw="
  [mod."cloud.google.com/go/auth"]
    version = "v0.20.0"
    hash = "sha256-HlKu/WvrK7oj5hgaAkpv9WAufMLfEVLiRJAdM5W6GVU="
  [mod."cloud.google.com/go/auth/oauth2adapt"]
    version = "v0.2.8"
    hash = "sha256-GoXFqAbp1WO1tDj07PF5EyxDYvCBP0l0qwxY2oV2hfc="
  [mod."cloud.google.com/go/compute/metadata"]
    version = "v0.9.0"
    hash = "sha256-VFqQwLJKyH1zReR/XtygEHP5UkI01T9BHEL0hvXtauo="
  [mod."cloud.google.com/go/iam"]
    version = "v1.11.0"
    hash = "sha256-cqK0LLViHAzK/XQEUWTF7OBTqdC59oWgdWr7v3JNcvE="
  [mod."cloud.google.com/go/monitoring"]
    version = "v1.29.0"
    hash = "sha256-Hn/YZtZle8ObXy8yft4pgiNslqScuCdVnK8ztPnyEqw="
  [mod."cloud.google.com/go/storage"]
    version = "v1.62.3"
    hash = "sha256-iWy8PDGTWxeVDEfyh5XzkUqxSkDTgU6Uk4Wij90AlF8="
  [mod."github.com/GoogleCloudPlatform/opentelemetry-operations-go/detectors/gcp"]
    version = "v1.33.0"
    hash = "sha256-1RlE7uCsgdQ1T0pIvMJQ5SRPqPzeWqrYGPzYHXQBhbQ="
  [mod."github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/metric"]
    version = "v0.57.0"
    hash = "sha256-vCsapCImRi4i0gfZVPeLWwj8BeMAmZRF7sGQzWMvMyE="
  [mod."github.com/GoogleCloudPlatform/opentelemetry-operations-go/internal/resourcemapping"]
    version = "v0.57.0"
    hash = "sha256-HMMjGdEbwBe26a5VKonuIr2qNu6xWaJ67pE1f6oI0TE="
  [mod."github.com/agnivade/levenshtein"]
    version = "v1.2.1"
    hash = "sha256-3XnCzf7tFgEE0MmjxvjfWaw6qK6mKLabFZ3c23JIH9Y="
  [mod."github.com/ardanlabs/bucky"]
    version = "v1.0.6"
    hash = "sha256-XjacSUsH4hnVKeiAKzeRZjyMU1qv1LlhkCpeJtzJ0oU="
  [mod."github.com/ardanlabs/conf/v3"]
    version = "v3.12.0"
    hash = "sha256-lywKaxHXxsGBNlIOu0c4kLPB4U3oaX0INu56qv6/V3A="
  [mod."github.com/ardanlabs/jinja"]
    version = "v1.4.0"
    hash = "sha256-0uOkEieDjWNUpJyUdL0YjhTCW0b9o3Mvipo9uka5x+Y="
  [mod."github.com/arl/statsviz"]
    version = "v0.8.0"
    hash = "sha256-rSItFJKW0u0LxOU0li9jR9vGeSM+R9tGVEktsuo8t5Q="
  [mod."github.com/aws/aws-sdk-go-v2"]
    version = "v1.42.0"
    hash = "sha256-NAB0Xf/I0LfFbi01v2Z5FTnbLyqOn9t4Ao0aBzS5hF4="
  [mod."github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream"]
    version = "v1.7.13"
    hash = "sha256-VgXaGmkg9zBu1zqZ+mIdGKnn2KO4485JHxC0fPuU258="
  [mod."github.com/aws/aws-sdk-go-v2/config"]
    version = "v1.32.25"
    hash = "sha256-fNbv39eDSjFPIJy6hk6tEPVkc0kFB9kAXgK3Ul42fpM="
  [mod."github.com/aws/aws-sdk-go-v2/credentials"]
    version = "v1.19.24"
    hash = "sha256-anvHM7aJJZnFU3kawdubTBmTTql/To1pBr5h7PoiOyA="
  [mod."github.com/aws/aws-sdk-go-v2/feature/ec2/imds"]
    version = "v1.18.29"
    hash = "sha256-FtNSP2uygw+Yp6y4kKFUhYR6Q5rqDp3YJOkdhxexSOE="
  [mod."github.com/aws/aws-sdk-go-v2/internal/configsources"]
    version = "v1.4.29"
    hash = "sha256-jYjF19qwFqSLsLpFdlaOMfRmqU1vu9l07OpKoKlRzJA="
  [mod."github.com/aws/aws-sdk-go-v2/internal/endpoints/v2"]
    version = "v2.7.29"
    hash = "sha256-hL/HovKQp7zxU5GJPph7jFhsoB9su6AVY0lPnCYIskM="
  [mod."github.com/aws/aws-sdk-go-v2/internal/v4a"]
    version = "v1.4.30"
    hash = "sha256-/5GUNIcQ8AFQNuEQtkZU9TNxl6YSYMODdivW2/KDhGM="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding"]
    version = "v1.13.12"
    hash = "sha256-YXMPMvr43AcyZw1fOeGhmNjYEfuE5xWmi/mALqjwx54="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/checksum"]
    version = "v1.9.22"
    hash = "sha256-WmabR8FaX2u/s3Le5oMzzOI7qAM3sa2UtmyUxui6lkA="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/presigned-url"]
    version = "v1.13.29"
    hash = "sha256-iITG6WwpmkK+p2ewOD3RJBX3iLPNa8vkeu7lunWUimI="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/s3shared"]
    version = "v1.19.29"
    hash = "sha256-D3sEAqOox+Fi/pBu//Ub9YfJZhnYhpbhj33n8QggmbI="
  [mod."github.com/aws/aws-sdk-go-v2/service/s3"]
    version = "v1.104.0"
    hash = "sha256-HDbY0XOHIVtB7X6sYua0HrfwGSxydGzTemi/tJlK4bw="
  [mod."github.com/aws/aws-sdk-go-v2/service/signin"]
    version = "v1.2.0"
    hash = "sha256-0aMJCT1dkqH/CwrDcfceOu/kcQoi7XGJgYIs9JKuA3U="
  [mod."github.com/aws/aws-sdk-go-v2/service/sso"]
    version = "v1.31.3"
    hash = "sha256-Ob6IivAmg3u71HicgFhneUBt5JhHTKV0epTPay6Butk="
  [mod."github.com/aws/aws-sdk-go-v2/service/ssooidc"]
    version = "v1.36.6"
    hash = "sha256-xrFdgWlq27aMffkZOn8pgH9y4cT0MOjGxh3LAR0rMwo="
  [mod."github.com/aws/aws-sdk-go-v2/service/sts"]
    version = "v1.43.3"
    hash = "sha256-WWav9rCwe7b8UH9JhJ9dc6BeJ/gHmRReSBhpPTg9l4E="
  [mod."github.com/aws/smithy-go"]
    version = "v1.27.2"
    hash = "sha256-xC/HVhXmeqwUP0IJmoUgsKsuAmag873kPb1NRHCucC0="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/bgentry/go-netrc"]
    version = "v0.0.0-20140422174119-9fd32a8b3d3d"
    hash = "sha256-NDxQzO5C5M/aDz5/pjUHfZUh4VwIXovbb3irtxWCwjY="
  [mod."github.com/cenkalti/backoff/v5"]
    version = "v5.0.3"
    hash = "sha256-bKq43PPD8RM6e7HePxHaO27traqm76bkvHcTVTQ+jeY="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/cncf/xds/go"]
    version = "v0.0.0-20260202195803-dba9d589def2"
    hash = "sha256-nCcna5Dwr8a+FgdSZt43VmoMds5U0FZta2vpJfdMOhs="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.2-0.20180830191138-d8f796af33cc"
    hash = "sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc="
  [mod."github.com/decred/dcrd/dcrec/secp256k1/v4"]
    version = "v4.4.1"
    hash = "sha256-FfHNUmNdqtxHP5OFxqlJJ5jiZ9unpjeLGJS2yHoaNfU="
  [mod."github.com/dgraph-io/badger/v4"]
    version = "v4.9.2"
    hash = "sha256-Y//8ZZ1WSg32cJ0zLXyZ8SWOamYXMArYauj+HvlFRRg="
  [mod."github.com/dgraph-io/ristretto/v2"]
    version = "v2.4.0"
    hash = "sha256-U7lgRlPXM3IZWaVeoiEpZinBRfVR5jVHzM5GEOonj0U="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/ebitengine/purego"]
    version = "v0.10.1"
    hash = "sha256-LiJz/PNyealSiA8m/OPE0JnF1XD17YtpIlhx44jd34U="
  [mod."github.com/envoyproxy/go-control-plane/envoy"]
    version = "v1.37.0"
    hash = "sha256-xxQd6objJVXpcQ8B7MznhqeQLoLWlyjlASnq2hJDp+k="
  [mod."github.com/envoyproxy/protoc-gen-validate"]
    version = "v1.3.3"
    hash = "sha256-NsI6A4CBVTpAq4gsmv66sMx0gvY0J0kF/t9zbtlRLr4="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.1.0"
    hash = "sha256-oePAjhI+dYRrMQAeUWnJ3o+PdHFU1tk1Z/R3/kGdjnw="
  [mod."github.com/go-jose/go-jose/v4"]
    version = "v4.1.4"
    hash = "sha256-MKoJKXup1jfwOyN8mHXu1CQ8fvFJTaEf3K2LVtNSRhc="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.3"
    hash = "sha256-Nnp/dEVNMxLp3RSPDHZzGbI8BkSNuZMX0I0cjWKXXLA="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/gobwas/glob"]
    version = "v0.2.3"
    hash = "sha256-hYHMUdwxVkMOjSKjR7UWO0D0juHdI4wL8JEy5plu/Jc="
  [mod."github.com/goccy/go-json"]
    version = "v0.10.6"
    hash = "sha256-/REW1EDZ3Ta45hrDNR9YTIlhkxQQI8OeK5TxBNJ47Ho="
  [mod."github.com/golang-jwt/jwt/v4"]
    version = "v4.5.2"
    hash = "sha256-rTSqYEPooi8Uu4aXMW6k9dynOV+URYTGzVmbG3EQ7uo="
  [mod."github.com/google/flatbuffers"]
    version = "v25.12.19+incompatible"
    hash = "sha256-NOYL9CWJgjdY1u4j/Ccyz2i50RjvZfNm/K+EFj7GIYk="
  [mod."github.com/google/go-cmp"]
    version = "v0.7.0"
    hash = "sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM="
  [mod."github.com/google/jsonschema-go"]
    version = "v0.4.3"
    hash = "sha256-AJDx6ZY91bQV0/mPHGDwko7+FgH/ihCH0kHubcbJIU4="
  [mod."github.com/google/s2a-go"]
    version = "v0.1.9"
    hash = "sha256-0AdSpSTso4bATmM/9qamWzKrVtOLDf7afvDhoiT/UpA="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/googleapis/enterprise-certificate-proxy"]
    version = "v0.3.16"
    hash = "sha256-8He6bIdZ92rh7JqLfCHBnIcziffbFOV/8XhueQNEeMA="
  [mod."github.com/googleapis/gax-go/v2"]
    version = "v2.22.0"
    hash = "sha256-EEoIpOYGDuzhiQdhJcpjMs4mSb2oMw3uPYRhCHCESR0="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.3"
    hash = "sha256-vTIGEFMEi+30ZdO6ffMNJ/kId6pZs5bbyqov8xe9BM0="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.29.0"
    hash = "sha256-a/J/iffTIqbKXIBGGKfPIjgfyb2F05jw3Au8f1q6yEk="
  [mod."github.com/hajimehoshi/go-mp3"]
    version = "v0.3.4"
    hash = "sha256-h6l0PuIS0h1zdB8MEqHTTgg8dE6nL6PSOt583ymaPnA="
  [mod."github.com/hashicorp/aws-sdk-go-base/v2"]
    version = "v2.0.0-beta.73"
    hash = "sha256-AHD3sIEA9eibc8NoLdVQWBRAJtGVwdYSoGYcDGFjXIE="
  [mod."github.com/hashicorp/go-cleanhttp"]
    version = "v0.5.2"
    hash = "sha256-N9GOKYo7tK6XQUFhvhImtL7PZW/mr4C4Manx/yPVvcQ="
  [mod."github.com/hashicorp/go-getter"]
    version = "v1.8.6"
    hash = "sha256-oN12gFUHqlF2J0h63wo8P1OSfuWeN8h4LJrBZvKHEvw="
  [mod."github.com/hashicorp/go-version"]
    version = "v1.9.0"
    hash = "sha256-sRr/50k8Wra0PJLCJgSkIxvR+ce3PItx4HpFvVijGYk="
  [mod."github.com/hybridgroup/yzma"]
    version = "v1.17.1"
    hash = "sha256-giiAIXEEP1JvOsi4CcudMugcnpZe/cx0Uy2zSDUWVHQ="
  [mod."github.com/icza/bitio"]
    version = "v1.1.0"
    hash = "sha256-CtV/dr1L46cZ65EnK9DrBduZCaMnTGf4N2MnElCymtM="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/jupiterrider/ffi"]
    version = "v0.7.0"
    hash = "sha256-9LUC4rq2yFmGar4HmYNjHB+WYfMLCOh2W4pMJjCrlw0="
  [mod."github.com/klauspost/compress"]
    version = "v1.18.6"
    hash = "sha256-gULc+A2Clg2HnwR9UNXSIHVGdFY/aGqhf0zlvMxqaSY="
  [mod."github.com/lestrrat-go/blackmagic"]
    version = "v1.0.4"
    hash = "sha256-HmWOpwoPDNMwLdOi7onNn3Sb+ZsAa3Ai3gVBbXmQ0e8="
  [mod."github.com/lestrrat-go/dsig"]
    version = "v1.3.0"
    hash = "sha256-GfTlvc3w+r/9VG2snmj9+0akAq7BCeh3rFBmUf0g9Yo="
  [mod."github.com/lestrrat-go/dsig-secp256k1"]
    version = "v1.0.0"
    hash = "sha256-kKdirGAHjx0lZPGPJCsvRVqPGTlFUGcF1SIvtXkUJRo="
  [mod."github.com/lestrrat-go/httpcc"]
    version = "v1.0.1"
    hash = "sha256-SMRSwJpqDIs/xL0l2e8vP0W65qtCHX2wigcOeqPJmos="
  [mod."github.com/lestrrat-go/httprc/v3"]
    version = "v3.0.6"
    hash = "sha256-gmHPNPCPq/Vn4s1PBYoSqlNaPNmXsnNTef9nL+6K+3M="
  [mod."github.com/lestrrat-go/jwx/v3"]
    version = "v3.1.1"
    hash = "sha256-yffwvtN4QQbN9TyvuUEABXKtOQJv7Trfw8qqz3HzKhw="
  [mod."github.com/lestrrat-go/option/v2"]
    version = "v2.0.0"
    hash = "sha256-ZmegDY7E3+tLd+kkNal1aeq3nfNH/dlWPpXOJfI3L5Q="
  [mod."github.com/maypok86/otter/v2"]
    version = "v2.3.0"
    hash = "sha256-ELzmi/s2WqDeUmzSGnfx+ys2Hs28XHqF7vlEzyRotIA="
  [mod."github.com/mewkiz/flac"]
    version = "v1.0.13"
    hash = "sha256-cQ10kMBZGiw7O0+cDW+Hr2LQVZbn1mM+op0vYIsR6sw="
  [mod."github.com/mewkiz/pkg"]
    version = "v0.0.0-20260331151047-10214ccde7de"
    hash = "sha256-Yp5hGzhrBON/jGHp16U4iLVfYd5NQPCcm7p7V2rmy7Y="
  [mod."github.com/mewpkg/term"]
    version = "v0.0.0-20241026122259-37a80af23985"
    hash = "sha256-WgvLJUMIXdYgpZivX38fZqaMTIimnpLdpRVsBhjEWZI="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/modelcontextprotocol/go-sdk"]
    version = "v1.6.1"
    hash = "sha256-NUE1/FngwSZ9z2JkQtno7WZIokuDhJRu/lusb/2il0g="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/open-policy-agent/opa"]
    version = "v1.17.1"
    hash = "sha256-yXPG4anLX1RN/PBVvwX25DTuZ4LXM++ZRP/G0Fab7Fo="
  [mod."github.com/planetscale/vtprotobuf"]
    version = "v0.6.1-0.20240319094008-0393e58bdf10"
    hash = "sha256-L8dyNm+PCRDNADiIGKZqsPkCgB4xpLrosZjssrN+sUY="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.1-0.20181226105442-5d4384ee4fb2"
    hash = "sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.23.2"
    hash = "sha256-3GD4fBFa1tJu8MS4TNP6r2re2eViUE+kWUaieIOQXCg="
  [mod."github.com/prometheus/client_model"]
    version = "v0.6.2"
    hash = "sha256-q6Fh6v8iNJN9ypD47LjWmx66YITa3FyRjZMRsuRTFeQ="
  [mod."github.com/prometheus/common"]
    version = "v0.69.0"
    hash = "sha256-rqui1G7KMtVtGXDFY7XpWD9tA721UtoPC+/JLh8axrA="
  [mod."github.com/prometheus/procfs"]
    version = "v0.20.1"
    hash = "sha256-L6RuVGYgdBCCke8BibA7cXgfwizGE2pA0gNo9dGJ8WQ="
  [mod."github.com/rcrowley/go-metrics"]
    version = "v0.0.0-20250401214520-65e299d6c5c9"
    hash = "sha256-xTuRRrDpI/ANi/cvRMerx+gHP/ePGT0MxHHB5UXMVus="
  [mod."github.com/segmentio/asm"]
    version = "v1.2.1"
    hash = "sha256-XhAJObkSa7gjx3PqYrreVEcMHBc/rDVeY/lWvNccGB0="
  [mod."github.com/segmentio/encoding"]
    version = "v0.5.4"
    hash = "sha256-AVIwCIh/L7X7CaGGX2gYOlurO/xifjjLpK+AIRTv2rQ="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.4"
    hash = "sha256-ltRvmtM3XTCAFwY0IesfRqYIivyXPPuvkFjL4ARh1wg="
  [mod."github.com/spf13/cobra"]
    version = "v1.10.2"
    hash = "sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.10"
    hash = "sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU="
  [mod."github.com/spiffe/go-spiffe/v2"]
    version = "v2.8.1"
    hash = "sha256-9rVvr5oguOnMBZYFv06cg/DuOUNxKAD+qO/Y85AXf0g="
  [mod."github.com/stretchr/testify"]
    version = "v1.11.1"
    hash = "sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc="
  [mod."github.com/tchap/go-patricia/v2"]
    version = "v2.3.3"
    hash = "sha256-6Ahy1QFyx3T0z5zghIGWBgfagdRGPLgrKYYcYvJj2ig="
  [mod."github.com/ulikunitz/xz"]
    version = "v0.5.15"
    hash = "sha256-L5KYLue5U14bxUuNyhZ6lIjbda6eCQsx1V6gToqfRdk="
  [mod."github.com/valyala/fastjson"]
    version = "v1.6.10"
    hash = "sha256-D2lL4FnkeL/eRLiRW6ihhqQkzEqHVvhbEvZoYTVNmbU="
  [mod."github.com/vektah/gqlparser/v2"]
    version = "v2.5.35"
    hash = "sha256-USS2GqgT0p1XLhj8x5hyTNqfcafNER1dYFOneZeTc0A="
  [mod."github.com/xeipuuv/gojsonpointer"]
    version = "v0.0.0-20190905194746-02993c407bfb"
    hash = "sha256-/u+qznDY8cnECZYIgSMRpKVWs04yAkW6EoGhqt+t73g="
  [mod."github.com/xeipuuv/gojsonreference"]
    version = "v0.0.0-20180127040603-bd5ef7bd5415"
    hash = "sha256-ZbXA+ASQrTgBQzasUKC9vznrOGpquYyWr+uwpm46fvU="
  [mod."github.com/yashtewari/glob-intersection"]
    version = "v0.2.0"
    hash = "sha256-SwTh5MEtGTqytNqlvoMWaEpVx9iABnnBJ6FzLJ5qg+s="
  [mod."github.com/yosida95/uritemplate/v3"]
    version = "v3.0.2"
    hash = "sha256-znUsCrfogPwAUNsdxBL93jIW/joercUm7RxKSExuWTM="
  [mod."go.opentelemetry.io/auto/sdk"]
    version = "v1.2.1"
    hash = "sha256-73bFYhnxNf4SfeQ52ebnwOWywdQbqc9lWawCcSgofvE="
  [mod."go.opentelemetry.io/contrib/detectors/gcp"]
    version = "v1.44.0"
    hash = "sha256-dp+EQTl8DCYVrRKEJ/IpRMUomgIRx/M0z2LkeCctwiY="
  [mod."go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"]
    version = "v0.69.0"
    hash = "sha256-37oe5RsiBWxaOs7lZXJWEUN4P49jkr2ej+64FQ4ybT8="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.69.0"
    hash = "sha256-ypZB41ebghWCNZmuoDgdGbWyTjCglBEirLZ+s7jqCgc="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.44.0"
    hash = "sha256-XTGV9RjOIKyWrrgXJ32IA59lovxXqSeRrpcpC1FAFZA="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.44.0"
    hash = "sha256-hqgoY2kWcu58Vdq+DrBZCT0g5bs/cnVLCcwYYWfinu4="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"]
    version = "v1.44.0"
    hash = "sha256-hQeEeRqWCiMr2m1GHWlIOSbA6YTHgW6EW+M3e26lDn0="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.44.0"
    hash = "sha256-e8dVyRoavby/YG7aH2T05IhWHlLvwnMHyPhelAS1mCQ="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.44.0"
    hash = "sha256-rNqJXr5P2f5Qgllp/3E5Rm5lqt1kBhxHXppT5dXw5Cw="
  [mod."go.opentelemetry.io/otel/sdk/metric"]
    version = "v1.44.0"
    hash = "sha256-9OJi3uCRMdCo0d5YZjJnPCveQ9JNifNoOUBOEPtNBBE="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.44.0"
    hash = "sha256-69HorWRTLLzAHRgLe4nPp13qJthb3qp7RU7c0Y9qV/c="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v1.10.0"
    hash = "sha256-IEnbR38ucFLTcuC2FA+gRvZNq2loUqXgDskSqP3+LUM="
  [mod."go.yaml.in/yaml/v2"]
    version = "v2.4.4"
    hash = "sha256-ecT2ZXw7iT+63J4210xA6sMz0fUFXmDzLwZe2FzaNFU="
  [mod."go.yaml.in/yaml/v3"]
    version = "v3.0.4"
    hash = "sha256-NkGFiDPoCxbr3LFsI6OCygjjkY0rdmg5ggvVVwpyDQ4="
  [mod."golang.org/x/crypto"]
    version = "v0.53.0"
    hash = "sha256-TWcccM4d5t0ZbDyHXEm4elxKk5uzlo29i85lVHSZcNw="
  [mod."golang.org/x/image"]
    version = "v0.43.0"
    hash = "sha256-GKd2YyREOkKGh4xfpgOo9eOc1gzzMRXrIEH1SmJ2688="
  [mod."golang.org/x/net"]
    version = "v0.56.0"
    hash = "sha256-JUORjxDZqZanYWo2yunaDpQ2/zvHiFb0TnF1Jw6D+30="
  [mod."golang.org/x/oauth2"]
    version = "v0.36.0"
    hash = "sha256-evS7WkMrpgonmTcqtWFpC5rSKZN8O+vnAhNUs1MS9kw="
  [mod."golang.org/x/sync"]
    version = "v0.21.0"
    hash = "sha256-2n7PVb1krz7UpnXYGVmCrxV0fZBnjQdVVt6eVudEPYY="
  [mod."golang.org/x/sys"]
    version = "v0.46.0"
    hash = "sha256-NzRXMSEk6upeudJvUEPVnw6clJ3d8UdC/vdfANWAc8g="
  [mod."golang.org/x/text"]
    version = "v0.38.0"
    hash = "sha256-PzREcn7yzTAJ0WBvyYL/2/r+tfoeKTY/E5HVXi/CJsU="
  [mod."golang.org/x/time"]
    version = "v0.15.0"
    hash = "sha256-5D24A65wn7k93Jj3+918UKjB9ccmGHPBEqjD2XDB92E="
  [mod."google.golang.org/api"]
    version = "v0.285.0"
    hash = "sha256-8FdFFQ2eEPHi2KAbf922d65Q9FyspyyspJjtnkUItnU="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20260618152121-87f3d3e198d3"
    hash = "sha256-MD+DSrFKsLyu3tamv2NNkWe1Yb1m9YTWR8iJEBBAWAg="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20260618152121-87f3d3e198d3"
    hash = "sha256-p69+PrsVk3bj1bB/wb03KvfVXWBPLqpj18SU0+C6in8="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20260618152121-87f3d3e198d3"
    hash = "sha256-ldJTTb7hhj1mdmzTn9IEkQVwCoj3KRlENZtUSEKHABU="
  [mod."google.golang.org/grpc"]
    version = "v1.81.1"
    hash = "sha256-YZ5KMHmN1HvsMxyIBIl3SmFmL3r+6bwjzzFLxUFhm1o="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.11"
    hash = "sha256-7W+6jntfI/awWL3JP6yQedxqP5S9o3XvPgJ2XxxsIeE="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."sigs.k8s.io/yaml"]
    version = "v1.6.0"
    hash = "sha256-49hg7IVPzwxeovp+HTMiWa/10NMMTSTjAdCmIv6p9dw="
